<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'combodo-mfa-totp/3.2.0',
	[
		// Identification
		//
		'label' => 'MFA TOTP mode',
		'category' => 'authentication',

		// Setup
		//
		'dependencies' => [
			'combodo-mfa-base/3.2.0',
		],
		'mandatory' => true,
		'visible' => true,

		// Components
		//
		'datamodel' => [
			'vendor/autoload.php',
			'model.combodo-mfa-totp.php', // Contains the PHP code generated by the "compilation" of datamodel.combodo-mfa-totp.xml
		],
		'webservice' => [

		],
		'data.struct' => [
			// add your 'structure' definition XML files here,
		],
		'data.sample' => [
			// add your sample data XML files here,
		],
		
		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => [
			// Module specific settings go here, if any
		],
	]
);

